name: setup-ninja

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: ${{ fromJSON(github.actor == 'dependabot[bot]' && '["ubuntu-latest"]' || '["windows-latest","ubuntu-latest","macos-latest"]') }}
        version: ${{ fromJSON(github.actor == 'dependabot[bot]' && '["1.12.1"]' || '["1.9.0","1.10.2","1.11.1","1.12.1"]') }}
        include: ${{ fromJSON(github.actor != 'dependabot[bot]' && '[{"image":"ubuntu-24.04-arm","version":"1.12.1"}]' || '[]') }}

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'package.json'
      - uses: ./
        with:
          version: '${{ matrix.version }}'
      - shell: bash
        run: '[ "$(ninja --version)" == "${{ matrix.version }}" ]'
